/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

/*import UIperso.RoundedButton;*/
import java.awt.Color;
import conexion.conexionMysql;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author dell
 */
public class frmlogin extends javax.swing.JFrame {
    
    private boolean isPasswordVisible = false;
    
    conexionMysql con = new conexionMysql();
    Connection cn = con.conectar();
    /**
     * Creates new form frmlogin
     */
    public static frmregister fr;
    public static frmMain fm;
    public frmlogin() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        IMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        vista = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        SignInBtn = new javax.swing.JPanel();
        signInTxt = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JPanel();
        registerTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(2, 21, 38));
        setMinimumSize(new java.awt.Dimension(705, 441));

        BgPanel.setBackground(new java.awt.Color(2, 21, 38));
        BgPanel.setName("Login"); // NOI18N
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 21, 38));
        jPanel1.setLayout(new java.awt.FlowLayout(1, 27, 27));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_unet_blanco.png"))); // NOI18N
        jPanel1.add(IMG);

        jLabel1.setFont(new java.awt.Font("Samsung Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("UNET Gamehub");
        jPanel1.add(jLabel1);

        BgPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 18, 790, 130));

        jPanel2.setBackground(new java.awt.Color(2, 21, 38));
        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 7));

        jPanel3.setMinimumSize(new java.awt.Dimension(254, 80));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(1084, 120));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel5.setOpaque(false);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel12.setMinimumSize(new java.awt.Dimension(244, 50));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(305, 50));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(1, 7, 6);
        flowLayout2.setAlignOnBaseline(true);
        jPanel12.setLayout(flowLayout2);

        Username.setBackground(new java.awt.Color(226, 226, 182));
        Username.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(226, 226, 226));
        Username.setText("Username:");
        Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Username.setMaximumSize(new java.awt.Dimension(105, 24));
        Username.setPreferredSize(new java.awt.Dimension(99, 24));
        jPanel12.add(Username);

        userTxt.setBackground(new java.awt.Color(2, 21, 38));
        userTxt.setColumns(15);
        userTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(226, 226, 226));
        userTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTxt.setText("username");
        userTxt.setAlignmentY(0.0F);
        userTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 242, 242)));
        userTxt.setMargin(new java.awt.Insets(2, 6, 10, 6));
        userTxt.setMaximumSize(new java.awt.Dimension(120, 20));
        userTxt.setMinimumSize(new java.awt.Dimension(100, 20));
        userTxt.setName(""); // NOI18N
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTxtMouseClicked(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel12.add(userTxt);

        jPanel5.add(jPanel12);

        jPanel3.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3);

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(1084, 100));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel10.setOpaque(false);

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel13.setMinimumSize(new java.awt.Dimension(297, 50));
        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(340, 50));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setBackground(new java.awt.Color(226, 226, 226));
        Password.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(226, 226, 226));
        Password.setText("Password:");
        Password.setToolTipText("");
        Password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Password.setPreferredSize(new java.awt.Dimension(90, 24));
        jPanel13.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 9, 90, 30));

        passTxt.setBackground(new java.awt.Color(2, 21, 38));
        passTxt.setColumns(12);
        passTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(226, 226, 226));
        passTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passTxt.setText("clavesegura12345");
        passTxt.setToolTipText("");
        passTxt.setActionCommand("<Not Set>");
        passTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 226, 226)));
        passTxt.setFocusCycleRoot(true);
        passTxt.setMargin(new java.awt.Insets(1, 9, 10, 29));
        passTxt.setMaximumSize(new java.awt.Dimension(12312, 20));
        passTxt.setMinimumSize(new java.awt.Dimension(120, 20));
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTxtMouseClicked(evt);
            }
        });
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        jPanel13.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 7, 170, 30));

        vista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vista.png"))); // NOI18N
        vista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vistaMousePressed(evt);
            }
        });
        jPanel13.add(vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 9, -1, -1));

        jPanel10.add(jPanel13);

        jPanel9.add(jPanel10, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel9);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.FlowLayout(1, 50, 29));

        SignInBtn.setBackground(new java.awt.Color(3, 52, 110));
        SignInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignInBtn.setMinimumSize(new java.awt.Dimension(70, 30));
        SignInBtn.setPreferredSize(new java.awt.Dimension(110, 70));
        SignInBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        signInTxt.setForeground(new java.awt.Color(207, 243, 255));
        signInTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInTxt.setText("Sign In");
        signInTxt.setAlignmentX(0.5F);
        signInTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInTxt.setMaximumSize(new java.awt.Dimension(150, 60));
        signInTxt.setMinimumSize(new java.awt.Dimension(120, 50));
        signInTxt.setName(""); // NOI18N
        signInTxt.setPreferredSize(new java.awt.Dimension(105, 50));
        signInTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInTxtMouseClicked(evt);
            }
        });
        SignInBtn.add(signInTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 50));

        jPanel14.add(SignInBtn);

        RegisterBtn.setBackground(new java.awt.Color(3, 52, 110));
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.setPreferredSize(new java.awt.Dimension(110, 72));
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterBtnMousePressed(evt);
            }
        });
        RegisterBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        registerTxt.setForeground(new java.awt.Color(207, 243, 255));
        registerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerTxt.setText("Register");
        registerTxt.setPreferredSize(new java.awt.Dimension(105, 70));
        registerTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerTxtMouseClicked(evt);
            }
        });
        RegisterBtn.add(registerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 49));

        jPanel14.add(RegisterBtn);

        jPanel7.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7);

        BgPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 790, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseClicked

        userTxt.setText("");

    }//GEN-LAST:event_userTxtMouseClicked

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void passTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseClicked

        passTxt.setText("");
    }//GEN-LAST:event_passTxtMouseClicked

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void vistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMousePressed
        if (isPasswordVisible) {
            passTxt.setEchoChar('*');  // Ocultar la contraseña
            isPasswordVisible = false;
        } else {
            passTxt.setEchoChar((char) 0);  // Mostrar la contraseña
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_vistaMousePressed

    private void registerTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerTxtMouseClicked
        this.dispose();
        fr=new frmregister();
        fr.setVisible(true);
    }//GEN-LAST:event_registerTxtMouseClicked

    private void RegisterBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMouseEntered

    private void RegisterBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMousePressed
       
    }//GEN-LAST:event_RegisterBtnMousePressed

    private void signInTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInTxtMouseClicked
        String username=userTxt.getText();
        String password=passTxt.getText();
        
        if(!username.equals("") || !password.equals("")){
            try{
                PreparedStatement  ps = cn.prepareStatement("SELECT user_id from users where username='"+username+"' and password='"+password+"'");
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    this.dispose();
                    int userId = rs.getInt("user_id");
                    fm= new frmMain();
                    fm.setVisible(true);
                    fm.setUserId(userId); // Pasar el user_id usando el método setter
                    fm.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuario o clave invalidos");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo logear el usuario "+ e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe llenar los Datos");
        }
    }//GEN-LAST:event_signInTxtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new frmlogin().setVisible(true);
                }
            });
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(frmlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JLabel IMG;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel RegisterBtn;
    private javax.swing.JPanel SignInBtn;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel registerTxt;
    private javax.swing.JLabel signInTxt;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel vista;
    // End of variables declaration//GEN-END:variables
}
