/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import conexion.conexionMysql;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author dell
 */
public class frmregister extends javax.swing.JFrame {
    conexion.conexionMysql con=new conexionMysql();
    Connection cn=con.conectar();
    public static frmlogin fl;
    private boolean isPasswordVisible = false;
    public frmregister() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("UnetGames");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BgPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        IMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        vista = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        SignInBtn = new javax.swing.JPanel();
        signInTxt = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JPanel();
        registerTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(797, 520));
        setPreferredSize(new java.awt.Dimension(797, 520));

        BgPanel.setBackground(new java.awt.Color(2, 21, 38));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 21, 38));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 27, 50));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_unet_blanco.png"))); // NOI18N
        jPanel1.add(IMG);

        jLabel1.setFont(new java.awt.Font("Samsung Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("UNET Gamehub");
        jPanel1.add(jLabel1);

        BgPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 797, 150));

        jPanel2.setBackground(new java.awt.Color(2, 21, 38));
        jPanel2.setLayout(new java.awt.GridLayout(5, 1));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(1084, 100));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel5.setOpaque(false);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel12.setMinimumSize(new java.awt.Dimension(244, 50));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(305, 50));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 9));

        Username.setBackground(new java.awt.Color(226, 226, 182));
        Username.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(226, 226, 226));
        Username.setText("Username:");
        Username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel12.add(Username);

        userTxt.setBackground(new java.awt.Color(2, 21, 38));
        userTxt.setColumns(15);
        userTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(226, 226, 226));
        userTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTxt.setText("username");
        userTxt.setAlignmentY(0.0F);
        userTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 242, 242)));
        userTxt.setMargin(new java.awt.Insets(2, 6, 10, 6));
        userTxt.setMaximumSize(new java.awt.Dimension(170, 20));
        userTxt.setMinimumSize(new java.awt.Dimension(130, 20));
        userTxt.setName(""); // NOI18N
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTxtMouseClicked(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        jPanel12.add(userTxt);

        jPanel5.add(jPanel12);

        jPanel3.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("");

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel10.setOpaque(false);
        jPanel6.setPreferredSize(jPanel6.getPreferredSize());
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanel10.setLayout(flowLayout1);
        jPanel9.add(jPanel10, new java.awt.GridBagConstraints());

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        Email.setBackground(new java.awt.Color(226, 226, 182));
        Email.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(226, 226, 226));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email:");
        Email.setToolTipText("");
        Email.setAlignmentY(1.0F);
        Email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Email.setPreferredSize(new java.awt.Dimension(50, 30));
        Email.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 32);
        jPanel11.add(Email, gridBagConstraints);

        emailTxt.setBackground(new java.awt.Color(2, 21, 38));
        emailTxt.setColumns(15);
        emailTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(226, 226, 226));
        emailTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailTxt.setText("example@unet.edu.ve");
        emailTxt.setAlignmentY(0.0F);
        emailTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 226, 226)));
        emailTxt.setMargin(new java.awt.Insets(1, 27, 1, 27));
        emailTxt.setMaximumSize(new java.awt.Dimension(196, 20));
        emailTxt.setMinimumSize(new java.awt.Dimension(166, 27));
        emailTxt.setPreferredSize(new java.awt.Dimension(160, 24));
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTxtMouseClicked(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 12, 19);
        jPanel11.add(emailTxt, gridBagConstraints);

        jPanel9.add(jPanel11, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel9);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridBagLayout());

        jPanel15.setOpaque(false);
        jPanel6.setPreferredSize(jPanel6.getPreferredSize());
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        jPanel15.setLayout(flowLayout2);

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(297, 50));
        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(360, 50));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setBackground(new java.awt.Color(226, 226, 226));
        Password.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(226, 226, 226));
        Password.setText("Password:");
        Password.setToolTipText("");
        Password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Password.setPreferredSize(new java.awt.Dimension(90, 24));
        jPanel8.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 9, 90, 30));

        passTxt.setBackground(new java.awt.Color(2, 21, 38));
        passTxt.setColumns(12);
        passTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(226, 226, 226));
        passTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passTxt.setText("clavesegura12345");
        passTxt.setToolTipText("");
        passTxt.setActionCommand("<Not Set>");
        passTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 226, 226)));
        passTxt.setFocusCycleRoot(true);
        passTxt.setMargin(new java.awt.Insets(1, 9, 10, 29));
        passTxt.setMaximumSize(new java.awt.Dimension(12312, 20));
        passTxt.setMinimumSize(new java.awt.Dimension(120, 20));
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTxtMouseClicked(evt);
            }
        });
        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        jPanel8.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 7, 165, 30));

        vista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vista.png"))); // NOI18N
        vista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vistaMousePressed(evt);
            }
        });
        jPanel8.add(vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 7, -1, -1));

        jPanel15.add(jPanel8);

        jPanel13.add(jPanel15, new java.awt.GridBagConstraints());

        jPanel6.setOpaque(false);
        jPanel13.add(jPanel6, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel13);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 90, 21));

        SignInBtn.setBackground(new java.awt.Color(3, 52, 110));
        SignInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signInTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        signInTxt.setForeground(new java.awt.Color(207, 243, 255));
        signInTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInTxt.setText("Sign In");
        signInTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignInBtnLayout = new javax.swing.GroupLayout(SignInBtn);
        SignInBtn.setLayout(SignInBtnLayout);
        SignInBtnLayout.setHorizontalGroup(
            SignInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        SignInBtnLayout.setVerticalGroup(
            SignInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInBtnLayout.createSequentialGroup()
                .addComponent(signInTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel14.add(SignInBtn);

        RegisterBtn.setBackground(new java.awt.Color(3, 52, 110));
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterBtnMousePressed(evt);
            }
        });

        registerTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        registerTxt.setForeground(new java.awt.Color(207, 243, 255));
        registerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerTxt.setText("Register");
        registerTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegisterBtnLayout = new javax.swing.GroupLayout(RegisterBtn);
        RegisterBtn.setLayout(RegisterBtnLayout);
        RegisterBtnLayout.setHorizontalGroup(
            RegisterBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );
        RegisterBtnLayout.setVerticalGroup(
            RegisterBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterBtnLayout.createSequentialGroup()
                .addComponent(registerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel14.add(RegisterBtn);

        jPanel7.add(jPanel14, java.awt.BorderLayout.PAGE_START);
        jPanel14.getAccessibleContext().setAccessibleName("");

        jPanel2.add(jPanel7);

        BgPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 797, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMousePressed

    private void RegisterBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMouseEntered

    private void registerTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerTxtMouseClicked
        String username=userTxt.getText();
        String email=emailTxt.getText();
        //String color=colorTxt.getText();
        String password=passTxt.getText();
        
        if(username.isEmpty() || email.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar los Datos");
        
        }
        else{
            try{
                String consulta = "INSERT INTO users(username, email, password)values('"+username+"', '"+email+"', '"+password+"')";
                PreparedStatement  ps = cn.prepareStatement(consulta);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Usuario creado correctamente.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo crear el usuario"+ e);
            }
        }
    }//GEN-LAST:event_registerTxtMouseClicked

    private void signInTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInTxtMouseClicked
        this.dispose();
        fl = new frmlogin();
        fl.setVisible(true);
    }//GEN-LAST:event_signInTxtMouseClicked

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseClicked
        
        userTxt.setText("");
        
    }//GEN-LAST:event_userTxtMouseClicked

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void emailTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseClicked
        emailTxt.setText("");
    }//GEN-LAST:event_emailTxtMouseClicked

    private void passTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseClicked

        passTxt.setText("");
    }//GEN-LAST:event_passTxtMouseClicked

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void vistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMousePressed
        if (isPasswordVisible) {
            passTxt.setEchoChar('*');  // Ocultar la contraseña
            isPasswordVisible = false;
        } else {
            passTxt.setEchoChar((char) 0);  // Mostrar la contraseña
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_vistaMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IMG;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel RegisterBtn;
    private javax.swing.JPanel SignInBtn;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel registerTxt;
    private javax.swing.JLabel signInTxt;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel vista;
    // End of variables declaration//GEN-END:variables
}
