/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;
import conexion.conexionMysql;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
/**
 *
 * @author dell
 */
public class frmregister extends javax.swing.JFrame {
    conexion.conexionMysql con=new conexionMysql();
    Connection cn=con.conectar();
    public static frmlogin fl;
    private boolean isPasswordVisible = false;
    public frmregister() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BgPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        IMG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Password = new javax.swing.JLabel();
        passTxt = new javax.swing.JPasswordField();
        SignInBtn = new javax.swing.JPanel();
        signInTxt = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JPanel();
        registerTxt = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        colorTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Email = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        vista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        BgPanel.setBackground(new java.awt.Color(2, 21, 38));

        jPanel1.setBackground(new java.awt.Color(2, 21, 38));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 50));

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_unet_blanco.png"))); // NOI18N
        jPanel1.add(IMG);

        jLabel1.setFont(new java.awt.Font("Samsung Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("UNET Gamehub");
        jPanel1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(2, 21, 38));

        Username.setBackground(new java.awt.Color(226, 226, 182));
        Username.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(226, 226, 182));
        Username.setText("Username:");

        userTxt.setBackground(new java.awt.Color(2, 21, 38));
        userTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(226, 226, 182));
        userTxt.setText("Enter your username");
        userTxt.setBorder(null);
        userTxt.setMaximumSize(new java.awt.Dimension(96, 22));
        userTxt.setMinimumSize(new java.awt.Dimension(96, 22));
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTxtMouseClicked(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        Password.setBackground(new java.awt.Color(226, 226, 182));
        Password.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(226, 226, 182));
        Password.setText("Password:");

        passTxt.setBackground(new java.awt.Color(2, 21, 38));
        passTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        passTxt.setForeground(new java.awt.Color(226, 226, 182));
        passTxt.setText("jPasswordField1");
        passTxt.setBorder(null);
        passTxt.setMaximumSize(new java.awt.Dimension(96, 22));
        passTxt.setMinimumSize(new java.awt.Dimension(96, 22));
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTxtMouseClicked(evt);
            }
        });

        SignInBtn.setBackground(new java.awt.Color(3, 52, 110));
        SignInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        signInTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        signInTxt.setForeground(new java.awt.Color(110, 172, 218));
        signInTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signInTxt.setText("Sign In");
        signInTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SignInBtnLayout = new javax.swing.GroupLayout(SignInBtn);
        SignInBtn.setLayout(SignInBtnLayout);
        SignInBtnLayout.setHorizontalGroup(
            SignInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        SignInBtnLayout.setVerticalGroup(
            SignInBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signInTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RegisterBtn.setBackground(new java.awt.Color(3, 52, 110));
        RegisterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterBtnMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegisterBtnMousePressed(evt);
            }
        });

        registerTxt.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        registerTxt.setForeground(new java.awt.Color(110, 172, 218));
        registerTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerTxt.setText("Register");
        registerTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerTxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegisterBtnLayout = new javax.swing.GroupLayout(RegisterBtn);
        RegisterBtn.setLayout(RegisterBtnLayout);
        RegisterBtnLayout.setHorizontalGroup(
            RegisterBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        RegisterBtnLayout.setVerticalGroup(
            RegisterBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        Color.setBackground(new java.awt.Color(226, 226, 182));
        Color.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Color.setForeground(new java.awt.Color(226, 226, 182));
        Color.setText("Color:");

        colorTxt.setBackground(new java.awt.Color(2, 21, 38));
        colorTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        colorTxt.setForeground(new java.awt.Color(226, 226, 182));
        colorTxt.setText("Enter your favorite color");
        colorTxt.setBorder(null);
        colorTxt.setMaximumSize(new java.awt.Dimension(96, 22));
        colorTxt.setMinimumSize(new java.awt.Dimension(96, 22));
        colorTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorTxtMouseClicked(evt);
            }
        });
        colorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTxtActionPerformed(evt);
            }
        });

        Email.setBackground(new java.awt.Color(226, 226, 182));
        Email.setFont(new java.awt.Font("Samsung Sans", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(226, 226, 182));
        Email.setText("Email:");

        emailTxt.setBackground(new java.awt.Color(2, 21, 38));
        emailTxt.setFont(new java.awt.Font("Samsung Sans", 0, 14)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(226, 226, 182));
        emailTxt.setText("Enter your email");
        emailTxt.setBorder(null);
        emailTxt.setMaximumSize(new java.awt.Dimension(96, 22));
        emailTxt.setMinimumSize(new java.awt.Dimension(96, 22));
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTxtMouseClicked(evt);
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        vista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vista.png"))); // NOI18N
        vista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vistaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(SignInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Color)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Username)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Email)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vista)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vista)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SignInBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BgPanelLayout = new javax.swing.GroupLayout(BgPanel);
        BgPanel.setLayout(BgPanelLayout);
        BgPanelLayout.setHorizontalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BgPanelLayout.setVerticalGroup(
            BgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseClicked
        userTxt.setText("");
    }//GEN-LAST:event_userTxtMouseClicked

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void passTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseClicked

        passTxt.setText("");

    }//GEN-LAST:event_passTxtMouseClicked

    private void colorTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorTxtMouseClicked
        // TODO add your handling code here:
        colorTxt.setText("");
    }//GEN-LAST:event_colorTxtMouseClicked

    private void colorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTxtActionPerformed
        
    }//GEN-LAST:event_colorTxtActionPerformed

    private void emailTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTxtMouseClicked
        emailTxt.setText("");
    }//GEN-LAST:event_emailTxtMouseClicked

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void RegisterBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMousePressed

    private void RegisterBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterBtnMouseEntered

    private void registerTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerTxtMouseClicked
        String username=userTxt.getText();
        String email=emailTxt.getText();
        String color=colorTxt.getText();
        String password=passTxt.getText();
        
        if(username.isEmpty() || email.isEmpty() || color.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe llenar los Datos");
        //Hay que hacer la query
        }
        else{
            try{
                String consulta = "INSERT INTO users(username,	email, color, password)values('"+username+"', '"+email+"', '"+color+"', '"+password+"')";
                PreparedStatement  ps = cn.prepareStatement(consulta);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Usuario creado correctamente.");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo crear el usuario"+ e);
            }
        }
    }//GEN-LAST:event_registerTxtMouseClicked

    private void signInTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInTxtMouseClicked
        this.dispose();
        fl = new frmlogin();
        fl.setVisible(true);
    }//GEN-LAST:event_signInTxtMouseClicked

    private void vistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMousePressed
        if (isPasswordVisible) {
            passTxt.setEchoChar('*');  // Ocultar la contraseña
            isPasswordVisible = false;
        } else {
            passTxt.setEchoChar((char) 0);  // Mostrar la contraseña
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_vistaMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BgPanel;
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel IMG;
    private javax.swing.JLabel Password;
    private javax.swing.JPanel RegisterBtn;
    private javax.swing.JPanel SignInBtn;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JLabel registerTxt;
    private javax.swing.JLabel signInTxt;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel vista;
    // End of variables declaration//GEN-END:variables
}
